ecommerse/ecommerseProject/cart/urls.py
from django.urls import path
from . import views


app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecommerse/ecommerseProject/ecommerseApp/urls.py
from django.urls import path
from . import views

app_name='ecommerseApp'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.productDetail,name='productCategoryDetail')
]

ecommerse/ecommerseProject/ecommerseProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerse/',include('ecommerseApp.urls')),
    path('search/',include('searchApp.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerse/ecommerseProject/searchApp/urls.py
from django.urls import path
from . import views


app_name='searchApp'

urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

ecommerse/ecommerseProject/cart/models.py
from django.db import models
from ecommerseApp.models import Product

# Create your models here.

class Cart(models.Model):
    cartId = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cartId

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerse/ecommerseProject/ecommerseApp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('ecommerseApp:products_by_category',args=[self.slug])

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('ecommerseApp:productCategoryDetail',args=[self.category.slug,self.slug])

ecommerse/ecommerseProject/searchApp/models.py
from django.db import models

# Create your models here.

ecommerse/ecommerseProject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerseApp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart= Cart.objects.get(cartId=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cartId=_cart_id(request)
        )
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist :
        cart_item = CartItem.objects.create(
            product=product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cartId=_cart_id(request))
        cart_items= CartItem.objects.filter(cart=cart,active=True)
        for item in cart_items:
            total += (item.product.price * item.quantity)
            counter += item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cartId=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cartId=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerse/ecommerseProject/ecommerseApp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.

def allProdCat(request,c_slug=None):
    c_page=None
    productsList=None
    if c_slug != None:
        c_page =get_object_or_404(Category,slug=c_slug)
        productsList = Product.objects.all().filter(category=c_page,available=True)
    else:
        productsList = Product.objects.all().filter(available=True)

    paginator = Paginator(productsList,6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page =1

    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})

def productDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerse/ecommerseProject/searchApp/views.py
from django.shortcuts import render
from ecommerseApp.models import Product
from django.db.models import Q

# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerse/ecommerseProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/c937f0ce00.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerse/ecommerseProject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is Your Cart. Proceed to review your items and place the order.
{% endblock %}
{% block title %}
    Cart -HOP Shop
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your Shopping Cart is Empty
                </h1>
                <br>
                <p class="text-center">
                    Please Add items. Click<a href="{% url 'ecommerseApp:allProdCat' %}">here</a>
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your Shopping Cart
                </h1>
                <br>
            </div>
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                                <th colspan="5">
                                    Your Items
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                                <tr>
                                    <td>
                                        <a href="item.product.get_absolute_url"><img src="{{item.product.img.url}}" alt="" style="width:100px; height:100px;" class="float-left rounded custom_image"></a>
                                    </td>
                                    <td class="text-left">
                                        {{item.product.name}}
                                        <br>
                                        SKU:{{item.product.id}}
                                        <br>
                                        Price: ${{item.product.price}}
                                        <br>
                                        Qty: {{item.quantity}} x $ {{item}}
                                    </td>
                                    <td>
                                        $ {{item.sub_total}}
                                    </td>
                                    {% if item.quantity < item.product.stock %}
                                        <td>
                                            <a href="{% url 'cart:add_cart' item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>
                                            &nbsp;
                                            <a href="{% url 'cart:cart_remove' item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                            &nbsp;
                                            <a href="{% url 'cart:full_remove' item.product_id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></i></a>
                                        </td>
                                    {% else %}
                                        <td>
                                            &nbsp;
                                            <a href="{% url 'cart:cart_remove' item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                            &nbsp;
                                            <a href="{% url 'cart:full_remove' item.product_id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></i></a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    Please review your shoping cart items before proceeding with the order payment.
                                </td>
                            </tr>
                            <tr>
                                <td class="text-left">
                                    Your Total is : <strong>{{ total }}</strong>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="mx-auto">
                        <a href="{% url 'ecommerseApp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
{% endblock %}

ecommerse/ecommerseProject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc |truncatewords:155 }}
    {% else %}
        Welcome to HOP Store where you can buys different items
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -- HOP Store
    {% else %}
        See our New Collections - Hop Stores
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p>
                        <a href="{% url 'ecommerseApp:allProdCat' %}">Our Product Collection</a>
                    </p>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{ category.img.url }}" alt="{{category.name}}">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.desc}}</p>
    </div>
        {% else %}
            <div>
                <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Our Products" style="width:1340px; height:400px;">
            </div>
            <br>
            <div>
                <h1 class="text-center">Our Product Collections</h1>
                <p class="text-justify">Filler text is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to
                display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter.</p>
            </div>
        {% endif %}

    <div class="container">
        <div class="row mx_auto">
            {% for prod in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width:18rem;">
                        <a href="{{ prod.get_url}}">
                            <img class="card-img-top my_image" src="{{prod.img.url}}" alt="{{prod.name}}">
                        </a>
                        <div class="card-body">
                            <h4>{{prod.name}}</h4>
                            <p>{{prod.price}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor  %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

ecommerse/ecommerseProject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; HOP pvt ltd.Reserved</p>
</div>

ecommerse/ecommerseProject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerseApp:allProdCat' %}">
            <img src="{% static 'img/logo.png' %}" alt="logo" style="width:80px; height:100px;">
        </a>
    </center>
</header>

ecommerse/ecommerseProject/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item dropdown {% if 'ecommerseApp' in request.path %} active {% endif %}" >
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Shop
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'ecommerseApp:allProdCat' %}">All Products</a></li>
                        {% for li in links %}
                            <li><a class="dropdown-item" href="{{li.get_url}}">{{li.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                {% if item_count > 0 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search" action="{% url 'searchApp:SearchResult' %}" method="get">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
        </div>
    </div>
</nav>

ecommerse/ecommerseProject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.desc |truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if product %}
        {{ product.name }} -- HOP Store
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row my_prod_row_class">
        <div class="mx_auto">
            <p>
                <a href="{% url 'ecommerseApp:allProdCat' %}">Home</a> |
                <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}
            </p>
        </div>
        <div class="container">

        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem;">
                <img src="{{product.img.url}}" alt="{{product.name}}">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p class="my_title">${{product.price}}</p>
                <p>Product Details:</p>
                <p class="text-justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text">
                        <b>Out Of Stock</b>
                    </p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To cart</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

ecommerse/ecommerseProject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have variety of Products.
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search_text">
            You have searched for : <b>{{query}}</b>
        </p>
    </div>
    <div class="container">
        <div class="row mx_auto">
            {% for prod in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width:18rem;">
                        <a href="{{ prod.get_url}}">
                            <img class="card-img-top my_image" src="{{prod.img.url}}" alt="{{prod.name}}">
                        </a>
                        <div class="card-body">
                            <h4>{{prod.name}}</h4>
                            <p>{{prod.price}}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="row mx-auto">
                    <p class="text-center my_search_text">0 results found</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}